# Generated by Django 5.2.11 on 2026-02-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.CharField(max_length=2)),
                ('hs2', models.CharField(max_length=2)),
                ('hs4', models.CharField(max_length=4)),
                ('description', models.TextField()),
                ('sector', models.CharField(max_length=255)),
                ('italy_to_india_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('india_to_italy_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['year'], name='core_trader_year_a734e5_idx'), models.Index(fields=['hs4'], name='core_trader_hs4_8a55c8_idx'), models.Index(fields=['sector'], name='core_trader_sector_1ead01_idx')],
            },
        ),
    ]
