# Generated by Django 5.2.11 on 2026-02-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderecord',
            name='hs2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='traderecord',
            name='hs4',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='traderecord',
            name='india_to_italy_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='traderecord',
            name='italy_to_india_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='traderecord',
            name='quarter',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='traderecord',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
