# Generated by Django 5.2.11 on 2026-02-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_traderecord_hs2_alter_traderecord_hs4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderecord',
            name='brochure2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='traderecord',
            name='hs2_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
