# Generated by Django 5.2.11 on 2026-02-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_traderecord_brochure2_traderecord_hs2_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderecord',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
