# Generated by Django 5.2.11 on 2026-03-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_keyword_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderecord',
            name='macrosector',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
