# Generated by Django 5.2.11 on 2026-03-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_traderecord_macrosector'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='traderecord',
            index=models.Index(fields=['hs2'], name='core_trader_hs2_b6bce6_idx'),
        ),
        migrations.AddIndex(
            model_name='traderecord',
            index=models.Index(fields=['brochure2'], name='core_trader_brochur_5c6fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='traderecord',
            index=models.Index(fields=['keyword'], name='core_trader_keyword_b0cfaf_idx'),
        ),
        migrations.AddIndex(
            model_name='traderecord',
            index=models.Index(fields=['macrosector'], name='core_trader_macrose_0d1b84_idx'),
        ),
        migrations.AddIndex(
            model_name='traderecord',
            index=models.Index(fields=['hs4', 'year'], name='core_trader_hs4_70470c_idx'),
        ),
        migrations.AddIndex(
            model_name='traderecord',
            index=models.Index(fields=['hs4', 'sector'], name='core_trader_hs4_a6eca5_idx'),
        ),
        migrations.AddIndex(
            model_name='traderecord',
            index=models.Index(fields=['year', 'hs2', 'hs4'], name='core_trader_year_1d32ce_idx'),
        ),
    ]
