# Generated by Codex on 2026-04-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_emailotp_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailOTP",
        ),
    ]
